// app/(main)/[business_urlname]/layout.tsx

import '@/app/styles/global.css';
import '@/app/styles/main.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
